### ISSUE TITLE
Build fails with "Build successful"

### ISSUE THREAD

**Issue by MasinAD** [arch-noob/filebot-git#2]
Well, at least makepkg fails with this message:
`BUILD SUCCESSFUL
Total time: 36 seconds
Reverting system jdk back to 
Wrong parameter count
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
`

When trying again "build failed", JAR archive is not a ZIP or something similar.

On third try, makepkg passes finally.

**Comment by rvasilev** [comment]
1. Whats the output of `archlinux-java get`?

2. You should probably run `makepkg --clean --cleanbuild` to get rid of "JAR archive is not a ZIP or something similar" on subsequent buildsfrom PKGBUILD.
