### ISSUE TITLE
upstream git repository got moved or removed

### ISSUE THREAD

**Issue by macearl** [arch-noob/filebot-git#5]
The filebot git repository does not seem to exist anymore

**Comment by rvasilev** [comment]
Investigating

**Comment by rvasilev** [comment]
https://www.filebot.net/forums/viewtopic.php?f=9&t=10871#p44867

> Yes, I've refactored things into a couple of private repositories, so I stopped commiting into the public one a few weeks ago. 

> I don't mind sending you a source tarball thought if you want, but what do you need it for anyway? As documentation for internals?

> I'm surprised somebody even noticed. Nobody seemed to contribute or comments on anything.

Looks like aur/filebot-git will be removed in the nearest future in favor of aur/filebot OR will be based on the latest author provided beta version.

**Comment by macearl** [comment]
to bad, looks like i need to find an open source solution...

**Comment by rvasilev** [comment]
https://alternativeto.net/software/medusa-tv-library-manager-/ there is sort of number of opensource solutions. @rednoah could send you a tarball of the sourcecode

**Comment by macearl** [comment]
yeah prior to filebot i tried a couple, but none just worked without having to rename the files manually to a point where i could have just done it completely myself.

Asking for a source tarball with each new release also does not seem practical... but it is his project (and business) so i respect his decision to go closed source

**Comment by rednoah** [comment]
Yes. Sorry for the inconvenience there. Note that the source is not required to run FileBot though.

The AUR build is officially available and supported, though you will have to purchase a license:
https://aur.archlinux.org/packages/filebot/
